### ISSUE TITLE
Need help on running the code.

### ISSUE THREAD

**Issue by ChenLiu-1996** [Kafri-Lab/Cell-Tracking#2]
Dear Daniel, Heather and members of the lab,

We are students from Columbia University working on a similar project where segmentation and tracking of cells are essential. The Cell-Tracking repository you shared was amazing and we particularly like the demo results. The only thing is we had some difficulties following through and running the code.

We currently are looking to segment and track the cells in a series of images. The nucleus images as well as cytoplasm images are both collected and can be used to perform the tracking. We would like to generate similar images as the frames in your demo video.

Here are our questions:
1. We are assuming that tracking_pipeline.m is the main go-to code to perform the cell tracking. Is that correct?
2. What is the ResultTable (required in tracking_pipeline.m) supposed to be? That is to say, what is it, where can I download a sample version or how can we construct our own?
3. Same question for the SubsetTable.

Thanks a lot for your time and willingness to help.

Best,
Raphael

**Comment by danielsnider** [comment]
Hi @ChenRaphaelLiu,

Are you sure you want to use Matlab? It is expensive so I recommend against it. If we continue you should be willing to dive into the code in case something isn't quite working. To continue download this [exe program](https://sickkidsca-my.sharepoint.com/:u:/g/personal/daniel_snider_sickkids_ca/EQD1tndauD5FmDbhIg8dxOMBQpWescglIfdrTBT-Jxfe1g?e=axE4QO)(link expires July 5th) which will help you produce the tracking results. Test that you can run the program and it opens okay. Then we'll setup a 1 hour online meeting with screensharing to try to perform nucleus tracking on your images. Do not accept unless you truly want to use Matlab 👎 and are willing to write matlab code if neccessary. I'm very sorry I don't have much time to help.

**Comment by ChenLiu-1996** [comment]
We actually went on to look for other approaches and over the weekend we brought together a bunch of ideas and came up with a version that worked fine on our data. Thanks for your nice comment and for sharing the link. We probably wouldn't need to schedule the meeting in this case. Thanks again for your help.

**Comment by danielsnider** [comment]
Hooray! Great going.
Daniel Snider ツ
